questions = {
    # --- BASICS ---
    "What is the keyword to define a function in Python?": "def",
    "Which data type is used to store True or False values?": "boolean",
    "What is the correct file extension for Python files?": ".py",
    "Which symbol is used to comment in Python?": "#",
    "What function is used to get input from the user?": "input",
    "How do you start a for loop in Python?": "for",
    "What is the output of 2 ** 3 in Python?": "8",
    "What keyword is used to import a module in Python?": "import",
    "What does the len() function return?": "length",
    "What is the result of 10 // 3 in Python?": "3",

    # --- CONTROL FLOW ---
    "Which keyword defines a class in Python?": "class",
    "What is the keyword to define a conditional statement?": "if",
    "What keyword is used to handle exceptions?": "try",
    "Which keyword is used to exit a loop prematurely?": "break",
    "Which keyword is used to skip to the next iteration in a loop?": "continue",
    "What keyword defines an anonymous function in Python?": "lambda",
    "Which keyword is used to define code that should run only if the script is executed directly?": "__main__",
    "Which keyword is used for the else-if condition in Python?": "elif",
    "Which keyword is used to create an infinite loop?": "while",
    "Which keyword is used to return a value from a function?": "return",

    # --- DATA TYPES ---
    "Which data type is used to store text in Python?": "string",
    "Which data type is used to store a list of items in order and can be changed?": "list",
    "Which data type stores items in key-value pairs?": "dictionary",
    "Which data type is ordered and immutable?": "tuple",
    "Which data type is unordered and contains unique values?": "set",
    "Which function checks the type of a variable?": "type",
    "Which function converts a string to an integer?": "int",
    "Which function converts a number to a string?": "str",
    "Which keyword is used to check if an element exists in a list?": "in",
    "Which function is used to display text on the screen?": "print",

    # --- OPERATORS & EXPRESSIONS ---
    "Which operator is used for string concatenation?": "+",
    "Which operator is used for exponentiation?": "**",
    "What will be the output of 5 % 2?": "1",
    "Which operator compares two values for equality?": "==",
    "Which operator assigns a value to a variable?": "=",
    "Which operator adds and assigns in one step?": "+=",
    "Which operator checks if two variables point to the same object?": "is",
    "What does '!=' mean in Python?": "not equal",
    "Which logical operator means both conditions must be true?": "and",
    "Which logical operator means at least one condition must be true?": "or",

    # --- STRINGS ---
    "What method converts text to uppercase?": "upper",
    "What method converts text to lowercase?": "lower",
    "What method removes whitespace from both ends of a string?": "strip",
    "Which method checks if a string contains only digits?": "isdigit",
    "Which method replaces parts of a string with another string?": "replace",
    "Which method splits a string into a list?": "split",
    "Which method joins a list into a string?": "join",
    "What will 'Python'[0] return?": "p",
    "What will 'Python'[-1] return?": "n",
    "What is the output of len('Hello')?": "5",

    # --- LISTS & COLLECTIONS ---
    "Which method adds an element to the end of a list?": "append",
    "Which method removes and returns the last element of a list?": "pop",
    "Which method removes an item by value from a list?": "remove",
    "Which method sorts a list in place?": "sort",
    "Which function returns the length of a list?": "len",
    "Which function returns the maximum value from a list?": "max",
    "Which function returns the minimum value from a list?": "min",
    "Which function returns the sum of all list elements?": "sum",
    "Which keyword is used to iterate through a list?": "for",
    "Which method reverses the elements of a list?": "reverse",

    # --- FILE HANDLING ---
    "Which keyword is used to open a file in Python?": "open",
    "What mode is used to read a file?": "r",
    "What mode is used to write to a file?": "w",
    "What mode is used to append to a file?": "a",
    "What method reads all lines from a file into a list?": "readlines",
    "What method closes an open file?": "close",
    "Which statement automatically closes a file after use?": "with",
    "What function checks if a file exists?": "exists",
    "Which module provides file system operations?": "os",
    "Which function gets the current working directory?": "getcwd",

    # --- FUNCTIONS & SCOPE ---
    "Which keyword is used to define a function parameter with a default value?": "=",
    "What keyword is used to indicate a variable is global?": "global",
    "What keyword is used to define a local scope inside a function?": "def",
    "What function returns the list of parameters passed to a function?": "args",
    "What function returns a dictionary of keyword arguments?": "kwargs",
    "Which keyword is used to create an iterator from a function?": "yield",
    "What function executes a string as Python code?": "eval",
    "Which function returns the absolute value of a number?": "abs",
    "Which function returns the rounded value of a number?": "round",
    "Which keyword prevents execution of empty code blocks?": "pass",

    # --- MODULES & PACKAGES ---
    "Which keyword imports everything from a module?": "from",
    "What built-in module is used for math operations?": "math",
    "Which function lists attributes and methods of an object?": "dir",
    "Which module provides random number generation?": "random",
    "Which module provides access to system-specific parameters?": "sys",
    "Which module handles date and time?": "datetime",
    "Which module allows you to work with JSON data?": "json",
    "Which module is used for regular expressions?": "re",
    "Which module allows you to pause execution?": "time",
    "Which module lets you interact with the operating system?": "os",

    # --- OOP ---
    "What is the first argument of any instance method?": "self",
    "Which method is the constructor in a Python class?": "__init__",
    "What keyword is used to create an object from a class?": "class_name()",
    "Which method is called automatically when an object is created?": "__init__",
    "Which keyword is used to inherit from another class?": "class child(parent)",
    "What is the process of hiding data called?": "encapsulation",
    "What is the process of reusing code from a parent class called?": "inheritance",
    "What is the process of defining methods with the same name but different behavior called?": "polymorphism",
    "Which method returns a string representation of an object?": "__str__",
    "Which method is called when an object is deleted?": "__del__",

    # --- ADVANCED / MISC ---
    "Which keyword raises an exception manually?": "raise",
    "Which keyword is used to handle exceptions after try?": "except",
    "Which keyword executes code after try/except blocks?": "finally",
    "What function returns an iterator from an iterable?": "iter",
    "What function retrieves the next item from an iterator?": "next",
    "Which comprehension creates a list from an iterable?": "list comprehension",
    "Which comprehension creates a dictionary from key-value pairs?": "dict comprehension",
    "Which comprehension creates a set from an iterable?": "set comprehension",
    "What is the output of bool(0)?": "false",
    "What is the output of bool(1)?": "true"
}
